// LOADING CONSTANTS
export const SET_LOADING = 'SET_LOADING';
export const CLEAR_LOADING = 'CLEAR_LOADING';

// MESSAGE/ERROR CONSTANTS
export const GET_MSG = 'GET_MSG';
export const GET_ERROR = 'GET_ERROR';
export const CLEAR_MSG = 'CLEAR_MSG';

export const TOKEN_EXPIRE = 'TOKEN_EXPIRE';


// AUTH CONSTANTS
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const EMAIL_VERIFIED_SUCCESS='EMAIL_VERIFIED_SUCCESS'
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const RESET_SUCCESS = 'RESET_SUCCESS';
export const RESET_FAIL = 'RESET_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const PROFILE_UPDATE_SUCCESS = 'PROFILE_UPDATE_SUCCESS';
export const PROFILE_UPDATE_FAIL = 'PROFILE_UPDATE_FAIL';

// MESSAGE/ERROR CONSTANTS
export const GET_TASK_SUCCESS = 'GET_TASK_SUCCESS';
export const GET_TASK_DETAIL_SUCCESS = 'GET_TASK_DETAIL_SUCCESS';
export const CREATE_TASK_SUCCESS = 'CREATE_TASK_SUCCESS';
export const GET_USER_TASK_SUCCESS = 'GET_USER_TASK_SUCCESS';
export const CREATE_TASK_FAIL = 'CREATE_TASK_FAIL';
export const UPDATE_TASK_SUCCESS = 'UPDATE_TASK_SUCCESS';
export const UPDATE_TASK_FAIL = 'UPDATE_TASK_FAIL';
export const TASK_COMPLETION_SUCCESS = 'TASK_COMPLETION_SUCCESS';
export const TASK_COMPLETION_FAIL = 'TASK_COMPLETION_FAIL';
export const DELETE_TASK_SUCCESS = 'DELETE_TASK_SUCCESS';
